docker:
  image: yegor256/rultor-ruby
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |-
  pdd -f /dev/null
  bundle install --no-color
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    bundle exec rake
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" iri.gemspec
    git add iri.gemspec
    git commit -m "Version set to ${tag}"
    gem build iri.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle exec rake
